services:
  api:
    container_name: exam1-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://exam1-db:3306/starbucks
      MYSQL_ROOT_PASSWORD: Por_160902
    depends_on:
      - database

  database:
    container_name: exam1-db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Por_160902
      MYSQL_DATABASE: starbucks

    volumes:
      - ./data:/var/lib/mysql